'use client';
import {useState,useEffect,useRef} from 'react';
import {Check,ChevronLeft,CreditCard,QrCode,ShieldCheck,CheckCircle2,KeyRound,Clock3,Copy,Eye,EyeOff,LockKeyhole} from 'lucide-react';
import {BrandLogo} from '../../components/brand-logo';
import '../storefront.css';
import {plans,getPlan,orderPlan,money,date,type PlanId,type Snapshot} from '../../lib/domain';
import './checkout.css';
export default function Checkout({initialPlanId}:{initialPlanId:PlanId}){
 const [planId,setPlanId]=useState<PlanId>(getPlan(initialPlanId)?.id??'mensal'),[method,setMethod]=useState<'pix'|'card'>('pix'),[data,setData]=useState<Snapshot|null>(null),[orderId,setOrderId]=useState(''),[stage,setStage]=useState<'review'|'payment'|'success'>('review'),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState(''),[copied,setCopied]=useState(''),[reveal,setReveal]=useState(false);
 const requestKey=useRef(''),heading=useRef<HTMLHeadingElement>(null),state=useRef({planName:'',amount:0,stage});
 const order=data?.orders.find(o=>o.id===orderId),plan=order?orderPlan(order):getPlan(planId)??plans[0],hasAccess=!!data&&data.account.expires_at>data.serverNow;
 useEffect(()=>{state.current={planName:plan.name,amount:plan.amount,stage}},[plan.name,plan.amount,stage]);
 async function load(){setLoading(true);setError('');try{const response=await fetch('/api/demo',{cache:'no-store'}),result=await response.json() as Snapshot&{error?:string};if(!response.ok)throw new Error(result.error??'Não foi possível carregar.');setData(result);const id=new URLSearchParams(location.search).get('pedido');if(id){const found=result.orders.find(o=>o.id===id);if(found){setOrderId(found.id);setPlanId(found.plan_id);setMethod(found.method);setStage(found.status==='paid'?'success':'payment')}else setError('Esse pedido não está disponível nesta conta. Você pode criar uma nova contratação.')}}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar sua compra.')}finally{setLoading(false)}}
 useEffect(()=>{requestKey.current=crypto.randomUUID();void load()},[]);
 useEffect(()=>{if(!loading)heading.current?.focus()},[stage]);
 useEffect(()=>{if(!copied)return;const timer=setTimeout(()=>setCopied(''),2500);return()=>clearTimeout(timer)},[copied]);
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'read_checkout_summary',description:'Read the selected example plan and current stage of the Aperte Play demonstration checkout. No payment is performed.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({mode:'demo',plan:state.current.planName,amount:state.current.amount,currency:'BRL',stage:state.current.stage})},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 async function act(body:Record<string,unknown>){setBusy(true);setError('');try{const response=await fetch('/api/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await response.json() as Snapshot&{error?:string;orderId?:string};if(!response.ok)throw new Error(result.error??'Não foi possível concluir.');setData(result);return result}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar. Tente novamente.');return null}finally{setBusy(false)}}
 async function create(){const result=await act({action:'create',planId,method,requestKey:requestKey.current});if(result?.orderId){setOrderId(result.orderId);history.replaceState(null,'','/comprar?plano='+planId+'&pedido='+result.orderId);setStage('payment')}}
 async function confirm(){if(await act({action:'confirm',orderId}))setStage('success')}
 function restart(){const nextPlanId=getPlan(planId)?.id??'mensal';setPlanId(nextPlanId);requestKey.current=crypto.randomUUID();setOrderId('');setStage('review');setError('');history.replaceState(null,'','/comprar?plano='+nextPlanId)}
 async function copy(value:string){try{await navigator.clipboard.writeText(value);setCopied('Dados copiados.')}catch{setCopied('Selecione o texto para copiar manualmente.')}}
 return <div className="storefront purchase-shell"><div className="sales-demo">Compra de demonstração <span>·</span> Nenhum valor será cobrado.</div><header className="sales-header purchase-header"><BrandLogo/><a href="/#planos" className="back-to-plans"><ChevronLeft size={16}/>Voltar aos planos</a></header><main className="purchase-main sales-container"><div className="purchase-progress" aria-label="Etapas da contratação">{['Seu plano','Pagamento','Seu acesso'].map((name,i)=>{const current=['review','payment','success'].indexOf(stage);return <div className={i===current?'current':i<current?'complete':''} key={name}><span>{i<current?<Check size={13}/>:i+1}</span>{name}</div>})}</div><div className="purchase-grid"><section className="purchase-panel"><p className="sales-kicker">{stage==='success'?'SEU PRÓXIMO PLAY ESTÁ MAIS PERTO':'FALTA POUCO PARA COMEÇAR'}</p><h1 ref={heading} tabIndex={-1}>{stage==='review'?'Vamos preparar seu acesso.':stage==='payment'?'Agora, o pagamento.':'Tudo certo. Seu acesso chegou.'}</h1><p className="purchase-intro">{stage==='review'?'Confira o plano e escolha como prefere pagar.':stage==='payment'?'Seu pedido está criado. Veja como será a confirmação.':'A confirmação atualiza seu acesso e o histórico da sua conta.'}</p>{loading&&<p className="purchase-status" role="status">Carregando sua contratação…</p>}{error&&<div className="purchase-error" role="alert"><p>{error}</p>{!data&&<button onClick={()=>void load()}>Tentar novamente</button>}</div>}
 {stage==='review'&&<><label className="purchase-label" htmlFor="checkout-plan">Seu período de acesso</label><select id="checkout-plan" value={planId} disabled={busy} onChange={e=>{setPlanId(e.target.value as PlanId);requestKey.current=crypto.randomUUID();history.replaceState(null,'','/comprar?plano='+e.target.value)}}>{plans.map(p=><option key={p.id} value={p.id}>{p.name.replace('Aperte Play ', '')} — {p.period} — {money(p.amount)}</option>)}</select><fieldset className="purchase-methods"><legend>Como prefere pagar?</legend><label className={method==='pix'?'selected':''}><input type="radio" name="method" value="pix" checked={method==='pix'} onChange={()=>{setMethod('pix');requestKey.current=crypto.randomUUID()}}/><QrCode size={24}/><strong>Pix</strong><span>Pagamento à vista</span></label><label className={method==='card'?'selected':''}><input type="radio" name="method" value="card" checked={method==='card'} onChange={()=>{setMethod('card');requestKey.current=crypto.randomUUID()}}/><CreditCard size={24}/><strong>Cartão</strong><span>Crédito ou débito*</span></label></fieldset><p className="method-footnote">*Modalidades sujeitas ao serviço de pagamento que será escolhido.</p><div className="purchase-callout"><ShieldCheck size={20}/><p>Você está usando uma conta de exemplo. Não informe dados bancários nesta apresentação.</p></div>{hasAccess&&<p className="existing-access">Esta conta já tem acesso até <strong>{date(data!.account.expires_at)}</strong>. A nova compra acrescenta {plan.days} dias à validade atual.</p>}<button className="sales-button purchase-primary" disabled={busy||loading||!data?.authenticated} onClick={()=>void create()}>{busy?'Preparando seu pedido…':'Continuar para pagamento'}</button>{!loading&&data&&!data.authenticated&&<a className="purchase-signin" href={'/signin-with-chatgpt?return_to='+encodeURIComponent('/comprar?plano='+planId)} target="_top">Entrar na demonstração para continuar</a>}<p className="purchase-fine">Pedido de teste. A etapa seguinte permite simular a aprovação.</p></>}
 {stage==='payment'&&order&&<><div className="payment-demo-block">{order.method==='pix'?<QrCode size={45}/>:<CreditCard size={45}/>}<h2>{order.method==='pix'?'Pix':'Cartão'} de demonstração</h2><p>{order.method==='pix'?'O QR Code e o código Pix aparecerão aqui quando o serviço de pagamento estiver conectado.':'O checkout seguro do serviço de pagamento será conectado nesta etapa. Não precisamos do número do seu cartão para demonstrar.'}</p><span>SEM COBRANÇA REAL</span></div><div className="purchase-order-row"><span>Pedido #{order.id.slice(0,8).toUpperCase()}</span><strong>{order.status==='pending'?'Aguardando confirmação':order.status==='cancelled'?'Pedido cancelado':'Pedido expirado'}</strong></div>{order.status==='pending'?<><button className="sales-button purchase-primary" disabled={busy} onClick={()=>void confirm()}><CheckCircle2 size={18}/>{busy?'Confirmando seu acesso…':'Simular pagamento aprovado'}</button><button className="purchase-cancel" disabled={busy} onClick={async()=>{const result=await act({action:'cancel',orderId});if(result)setCopied('Pedido de teste cancelado.')}}>Cancelar pedido de teste</button><p className="purchase-fine">Em uma compra real, a confirmação virá do serviço de pagamento. Este pedido de teste vence em 30 minutos.</p></>:<button className="sales-button purchase-primary" onClick={restart}>Criar um novo pedido</button>}</>}
 {stage==='success'&&data&&order&&<><div className="purchase-success"><span><Check size={29}/></span><div><h2>Pagamento de teste aprovado</h2><p>{plan.days} dias adicionados ao seu acesso.</p></div></div><div className="purchase-credentials"><div><span>Usuário</span><strong>{data.account.username}</strong><button onClick={()=>void copy(data.account.username)} aria-label="Copiar usuário"><Copy size={17}/></button></div><div><span>Senha</span><strong>{reveal?data.account.password:'••••••••••••••'}</strong><button onClick={()=>setReveal(!reveal)} aria-label={reveal?'Ocultar senha':'Mostrar senha'}>{reveal?<EyeOff size={17}/>:<Eye size={17}/>}</button><button onClick={()=>void copy(data.account.password)} aria-label="Copiar senha"><Copy size={17}/></button></div><div><span>Validade do acesso</span><strong>{date(data.account.expires_at)}</strong></div></div><p className="purchase-fine">Esses dados são fictícios e não conectam a um serviço IPTV. Na operação real, o fornecedor emitirá os acessos.</p><a className="sales-button purchase-primary" href="/area-do-cliente">Acessar minha área do cliente</a><a className="purchase-help" href="/area-do-cliente#devices">Ver orientações para assistir</a></>}
 {copied&&<p className="purchase-toast" role="status">{copied}</p>}</section><aside className="purchase-summary"><div className="summary-cover"><span>APERTE PLAY</span><KeyRound size={27}/><h2>{plan.name}</h2><p>{plan.period} de acesso</p></div><div className="summary-body"><div><span>Plano {plan.name.replace('Aperte Play ','')}</span><strong>{money(plan.amount)}</strong></div><div><span>Período</span><strong>{plan.period}</strong></div><div className="summary-total"><span>Total</span><strong>{money(plan.amount)}</strong></div><p>Valor total pelo período. Pagamento em demonstração.</p><ul><li><Check size={16}/>Acesso entregue na sua conta</li><li><Check size={16}/>Orientações de instalação</li><li><Check size={16}/>Renovação pelo site</li></ul></div><div className="summary-bottom"><LockKeyhole size={17}/><p>Nenhum dado bancário é coletado nesta demonstração.</p></div></aside></div></main><footer className="purchase-footer">Aperte Play <span>Seu acesso, em um só lugar.</span><a href="/#duvidas">Precisa de ajuda?</a></footer></div>
}
