import assert from 'node:assert/strict';
const base='http://127.0.0.1:5173';
const login=await fetch(base+'/signin-with-chatgpt?return_to=%2F',{redirect:'manual'});
const cookie=login.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ');
assert.ok(cookie,'Local sign-in must return a cookie.');
let checks=0;
const check=(actual,expected,message)=>{assert.deepEqual(actual,expected,message);checks++};
async function request(body,{auth=true,origin=base}={}){const r=await fetch(base+'/api/demo',{method:body?'POST':'GET',headers:{...(auth?{cookie}:{}),...(body?{'Content-Type':'application/json',Origin:origin}:{})},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={error:text}}return {status:r.status,data};}
check((await request({action:'reset',confirm:'RESET_DEMO',scenario:'new'},{auth:false})).status,401,'Anonymous writes must fail');
check((await request({action:'reset',confirm:'RESET_DEMO',scenario:'new'},{origin:'https://invalid.example'})).status,403,'Cross-origin writes must fail');
check((await fetch(base+'/api/checkout',{method:'POST'})).status,503,'Real checkout is disabled');
let s=await request({action:'reset',confirm:'RESET_DEMO',scenario:'new'});check(s.status,200,'Initialize new customer');check(s.data.account.expires_at,0,'New customer has no access');
check((await request({action:'create',planId:'invalid',method:'pix',requestKey:crypto.randomUUID()})).status,400,'Unknown plan rejected');
const key=crypto.randomUUID();
const first=await request({action:'create',planId:'mensal',method:'pix',requestKey:key,amount:1});
check(first.status,200,'Create order');check(first.data.orders[0].amount,2990,'Server controls price');check(first.data.account.expires_at,0,'Pending payment must not activate access');
const repeat=await request({action:'create',planId:'mensal',method:'pix',requestKey:key});check(first.data.orderId,repeat.data.orderId,'Creation is idempotent');check(repeat.data.orders.length,1,'One order per request');
const id=first.data.orderId;const confirmations=await Promise.all([request({action:'confirm',orderId:id}),request({action:'confirm',orderId:id})]);
check(confirmations.map(x=>x.status),[200,200],'Concurrent duplicate confirmation succeeds safely');
s=await request();const firstExpiry=s.data.account.expires_at;assert.ok(firstExpiry>Date.now()+29*86400000&&firstExpiry<Date.now()+31*86400000);checks++;
check(s.data.orders[0].applied,1,'Order fulfilled exactly once');
const again=await request({action:'confirm',orderId:id});check(again.data.account.expires_at,firstExpiry,'Duplicate does not add more days');
const renewal=await request({action:'create',planId:'trimestral',method:'card',requestKey:crypto.randomUUID()});
const renewed=await request({action:'confirm',orderId:renewal.data.orderId});check(renewed.data.account.expires_at,firstExpiry+90*86400000,'Renewal preserves remaining days');
const cancelled=await request({action:'create',planId:'mensal',method:'pix',requestKey:crypto.randomUUID()});
await request({action:'cancel',orderId:cancelled.data.orderId});check((await request({action:'confirm',orderId:cancelled.data.orderId})).status,400,'Cancelled order cannot activate');
check((await request({action:'confirm',orderId:crypto.randomUUID()})).status,400,'Unknown order rejected');
const chatted=await request({action:'chat',message:'Como renovar?'});check(chatted.data.messages.length,2,'Chat saves both sides');assert.match(chatted.data.messages[1].body,/validade/);checks++;
const reread=await request();check(reread.data.account.expires_at,renewed.data.account.expires_at,'State persists on reload');
await request({action:'reset',confirm:'RESET_DEMO',scenario:'active'});
console.log(JSON.stringify({passed:checks,result:'All local demo integration checks passed. Demo reset to active example.'}));
